// <auto-generated />
using System;
using EnocaAssignment.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnocaAssignment.Application.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20221127163434_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EnocaAssigment.Domain.Data.FilmHallModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FilmModelId")
                        .HasColumnType("int");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmHallModels");
                });

            modelBuilder.Entity("EnocaAssigment.Domain.Data.FilmModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FilmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FilmReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FilmModels");
                });

            modelBuilder.Entity("EnocaAssigment.Domain.Data.FilmSessionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("FilmExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmHallModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FilmReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FilmHallModelId");

                    b.ToTable("FilmSeassionModels");
                });

            modelBuilder.Entity("EnocaAssigment.Domain.Data.FilmHallModel", b =>
                {
                    b.HasOne("EnocaAssigment.Domain.Data.FilmModel", "FilmModel")
                        .WithMany("FilmHallModels")
                        .HasForeignKey("FilmModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmModel");
                });

            modelBuilder.Entity("EnocaAssigment.Domain.Data.FilmSessionModel", b =>
                {
                    b.HasOne("EnocaAssigment.Domain.Data.FilmHallModel", "FilmHallModel")
                        .WithMany("FilmSessionModels")
                        .HasForeignKey("FilmHallModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmHallModel");
                });

            modelBuilder.Entity("EnocaAssigment.Domain.Data.FilmHallModel", b =>
                {
                    b.Navigation("FilmSessionModels");
                });

            modelBuilder.Entity("EnocaAssigment.Domain.Data.FilmModel", b =>
                {
                    b.Navigation("FilmHallModels");
                });
#pragma warning restore 612, 618
        }
    }
}
